cephClusterSpec:
  cephVersion:
    # renovate: image=quay.io/ceph/ceph
    image: ###ZARF_REGISTRY###/ceph/ceph:v18.2.2

  network:
    # Use host networking to avoid CNI causing storage issues
    provider: host
    # Encrypt connections to/from storage
    connections:
      encryption:
        enabled: true

  # Use select devices for storage
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: "###ZARF_VAR_DEVICE_FILTER###"

  mon:
    count: "###ZARF_VAR_HA_REPLICAS###"
    allowMultiplePerNode: "###ZARF_VAR_IS_HA_CLUSTER###"

  osd:
    count: "###ZARF_VAR_HA_REPLICAS###"

  mgr:
  count: "###ZARF_VAR_HA_REPLICAS###"
  modules:
    - enabled: true
      name: pg_autoscaler

imagePullSecrets:
  - name: private-registry

# UDS Rook-Ceph Config chart is used to deploy the below resources so defaults are nulled out
cephBlockPools: []
cephFileSystems: []
cephObjectStores: []
