cephClusterSpec:
  cephVersion:
    # renovate: image=quay.io/ceph/ceph
    image: ###ZARF_REGISTRY###/ceph/ceph:v18.2.1

  network:
    # Use host networking to avoid CNI causing storage issues
    provider: host
    # Encrypt connections to/from storage
    connections:
      encryption:
        enabled: true

  # Use select devices for storage
  storage:
    useAllNodes: true
    useAllDevices: true
    deviceFilter: "###ZARF_VAR_DEVICE_FILTER###"

imagePullSecrets:
  - name: private-registry

# Installs a debugging toolbox deployment
toolbox:
  # -- Enable Ceph debugging pod deployment. See [toolbox](https://github.com/rook/rook/blob/master/Documentation/Troubleshooting/ceph-toolbox.md)
  enabled: true

# UDS Rook-Ceph Config chart is used to deploy the below resources so defaults are nulled out
cephBlockPools: []
cephFileSystems: []
cephObjectStores: []
