cephClusterSpec:
  cephVersion:
    image: registry1.dso.mil/ironbank/opensource/ceph/ceph:v17.2.6 # v18 IB image not fully functional, upstream chart has v17 by default

  network:
    # Use host networking to avoid CNI causing storage issues
    provider: host
    # Encrypt connections to/from storage
    connections:
      encryption:
        enabled: true

  # Use select devices for storage
  storage:
    useAllNodes: true
    # Configure device filter
    useAllDevices: ###ZARF_VAR_USE_ALL_DEVICES###
    config:
      deviceFilter: "###ZARF_VAR_DEVICE_FILTER###"
      # Separate metadata device to smaller + faster device
      # metadataDevice: "sdb"

imagePullSecrets:
  - name: private-registry
