image:
  repository: ###ZARF_REGISTRY###/ironbank/rook/ceph
  # renovate: image=registry1.dso.mil/ironbank/rook/ceph
  tag: v1.14.0

csi:
  cephFSKernelMountOptions: "ms_mode=secure"

  readAffinity:
    enabled: true

  cephcsi:
    repository: ###ZARF_REGISTRY###/ironbank/opensource/ceph/ceph-csi
    # renovate: image=registry1.dso.mil/ironbank/opensource/ceph/ceph-csi
    tag: v3.11.0

  registrar:
    repository: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-node-driver-registrar
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-node-driver-registrar
    tag: v2.10.1

  provisioner:
    repository: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-provisioner
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-provisioner
    tag: v4.0.1

  snapshotter:
    repository: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-snapshotter
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-snapshotter
    tag: v7.0.2

  attacher:
    repository: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-attacher
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-attacher
    tag: v4.5.1

  resizer:
    repository: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-resizer
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-resizer
    tag: v1.10.1

imagePullSecrets:
  - name: private-registry

# -- Runs Ceph Pods as privileged to be able to write to `hostPaths` in environments with SELinux restrictions.
hostpathRequiresPrivileged: true
