image:
  repository: ###ZARF_REGISTRY###/ironbank/rook/ceph
  # renovate: image=registry1.dso.mil/ironbank/rook/ceph
  tag: v1.13.2

csi:
  cephFSKernelMountOptions: "ms_mode=secure"

  readAffinity:
    enabled: true

  cephcsi:
    # renovate: image=registry1.dso.mil/ironbank/opensource/ceph/ceph-csi
    image: ###ZARF_REGISTRY###/ironbank/opensource/ceph/ceph-csi:v3.10.1

  registrar:
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-node-driver-registrar
    image: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-node-driver-registrar:v2.10.0

  provisioner:
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-provisioner
    image: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-provisioner:v4.0.0

  snapshotter:
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-snapshotter
    image: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-snapshotter:v6.3.3

  attacher:
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-attacher
    image: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-attacher:v4.5.0

  resizer:
    # renovate: image=registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-resizer
    image: ###ZARF_REGISTRY###/ironbank/opensource/kubernetes-sigs/sig-storage/csi-resizer:v1.10.0

imagePullSecrets:
  - name: private-registry

# -- Runs Ceph Pods as privileged to be able to write to `hostPaths` in environments with SELinux restrictions.
hostpathRequiresPrivileged: true
