image:
  repository: registry1.dso.mil/ironbank/rook/ceph
  tag: v1.12.7

csi:
  cephFSKernelMountOptions: "ms_mode=secure"

  readAffinity:
    enabled: true

  cephcsi:
    image: registry1.dso.mil/ironbank/opensource/ceph/ceph-csi:v3.9.0

  registrar:
    image: registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-node-driver-registrar:v2.9.0

  provisioner:
    image: registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-provisioner:v3.6.2

  snapshotter:
    image: registry.k8s.io/sig-storage/csi-snapshotter:v6.3.1

  attacher:
    image: registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-attacher:v4.4.1

  resizer:
    image: registry.k8s.io/sig-storage/csi-resizer:v1.9.1

imagePullSecrets:
  - name: private-registry

# -- Runs Ceph Pods as privileged to be able to write to `hostPaths` in OpenShift with SELinux restrictions.
hostpathRequiresPrivileged: ###ZARF_VAR_PRIVILEGED_HOSTPATH###
