image:
  repository: registry1.dso.mil/ironbank/rook/ceph
  tag: v1.12.6

csi:
  cephFSKernelMountOptions: "ms_mode=secure"

  readAffinity:
    enabled: true

  cephcsi:
    image: registry1.dso.mil/ironbank/opensource/ceph/ceph-csi:v3.9.0

  registrar:
    image: registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-node-driver-registrar:v2.9.0

  provisioner:
    image: registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-provisioner:v3.6.1

  snapshotter:
    image: registry.k8s.io/sig-storage/csi-snapshotter:v6.2.3

  attacher:
    image: registry1.dso.mil/ironbank/opensource/kubernetes-sigs/sig-storage/csi-attacher:v4.2.0

  resizer:
    image: registry.k8s.io/sig-storage/csi-resizer:v1.9.1

imagePullSecrets:
  - name: private-registry
