package:
  create:
    max_package_size: "1000000000"
    # These values are sourced from and updated with https://github.com/defenseunicorns/zarf/blob/main/zarf-config.toml
    set:
      agent_image_domain: "ghcr.io/"
      agent_image: "defenseunicorns/zarf/agent"

      injector_version: "2023-08-02"
      injector_amd64_shasum: "91de0768855ee2606a4f85a92bb480ff3a14ca205fd8d05eb397c18e15aa0247"
      injector_arm64_shasum: "663df681deea957b0ec53538eab221691a83de8e95d86b8a29008af711934bee"

      registry_image_domain: ""
      registry_image: "library/registry"
      registry_image_tag: "2.8.3"

      gitea_image: "gitea/gitea:1.21.2-rootless"

  deploy:
    set:
      # -- Regular expression matching all devices to use for Ceph storage, example "^sd."
      # If not provided all unformatted devices and partitions will be formatted for Ceph.
      device_filter: ""
      # HA configurations
      is_ha_cluster: true
      ha_replicas: 3
      active_metadata_servers: 1
      region: us-east-1
