name: Publish Zarf Package

on:
  workflow_call:

permissions:
  contents: read
  packages: write

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Registry1
        uses: docker/login-action@v2
        with:
          registry: registry1.dso.mil
          username: ${{ secrets.REGISTRY1_USERNAME }}
          password: ${{ secrets.REGISTRY1_PASSWORD }}

      - name: Install Zarf
        uses: defenseunicorns/setup-zarf@main
        with:
          # renovate: datasource=github-tags depName=defenseunicorns/zarf versioning=semver
          version: v0.29.1
          download-init-package: true

      - name: Create Package
        run: ./scripts/helper.sh create-zarf-package

      - name: Create Cluster
        run: ./scripts/helper.sh create-cloud-cluster

      - name: Zarf Init
        run: ./scripts/helper.sh zarf-init

      - name: Deploy Package
        run: ./scripts/helper.sh deploy-zarf-package

      - name: Test Package
        run: ./scripts/helper.sh test-zarf-package

      - name: Debug Output
        if: always()
        run: ./scripts/helper.sh debug-output

      - name: Remove Package
        if: always()
        run: ./scripts/helper.sh remove-zarf-package

      - name: Delete Cluster
        if: always()
        run: ./scripts/helper.sh delete-cloud-cluster

      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: rook-ceph-publisher
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish Zarf Package
        run: ./scripts/helper.sh publish-zarf-package
        timeout-minutes: 60
